version: '3.8'
services:
 catelogdb:
  image: postgres:16-alpine

 basketdb:
    image: postgres:16-alpine

 distributedcache:
  image: redis

 catelog.api:
  image: ${DOCKER_REGISTRY-}catelog.api:latest 
  build:
    context: .
    dockerfile: src/Services/Catelog/Catelog.API/Dockerfile

 basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

 discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grps/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:



