name: hello world
on: 
 push:
  branches:
    - main
    - develop
    - 'release/**'
 pull_request:
  types:
  - opened
  branches:
    - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Build Steps
       run: echo "A Demo Build variable value is ${{vars.My_Name}} and secrete is ${{secrets.My_Sec}}"
